### PR TITLE
Fields module staging

### PR DESCRIPTION
**Pull request by StephenJamesCashen**
The Fields visualization module and a couple of tutorials most else has been trimmed to limit the scope of the PR. Included also is the utilities module which is a dependency. 

The utilities module has a lot of useful functions in it. I would like to follow up with a tutorial for it in the near future. 

Future work for the fields module are methods to generate mp4 animations of visualizations. I have most of the code for this already, I just need to integrate it into the class and refactor. In addition a method to calculate mode volume, doing it for some of the common definitions has proven tricky, it may be productive to have a discussion about it. 

Finally a more rigorous regime of testing is warranted.

### CODE REVIEW

**Comment by momchilmm** [comment]
Thanks for all this! 

It''s quite a lot of code, so it will take some time to go through it. I'll try to get started on the weekend. Meanwhile I had a quick look and I just have a few global comments:

- Is there really a need for a chickpea module separate from legume? What is the reasoning there?
- What kind of linter did you use? I actually didn't use any back when I wrote it and there's nothing automatically set up, but I did use an 80 line length limit. However I'm not against removing it - maybe we should just unify the linting though.
- Related, I used the numpy docstring notation while you are using something else (I know it's also common, not sure what's the name though). It would be good to unify but at this point if there's no automatic way to do it, I guess we can live with it.

**Comment by ianwilliamson** [comment]
It looks like this contains a lot of non functional whitespace changes. Please apply those in a separate PR and then rebase this PR onto that one. Like @momchilmm says, the formatting hasn't really been standardized. I would vote for [`yapf`](https://github.com/google/yapf) with the default pep8 formatting, but am open to other suggestions.

+1 on keeping docstring notation standard.

**Comment by StephenJamesCashen** [comment]
Hi All, 

Thank you for the comments. In response to Momchil's:

- This is an artifact of internal development, I agree it should be changed. There are a couple ways to do this, one is to move the chickpea module under the legume package the other is to forgoe the chickpea name altogether and place everything under legume directly. Which would you suggest?

- I am using PyCharm as my developing environment which has its own default linter following the PEP 8 style guide. Yapf can be integrated into it. @ianwilliamson what is the difference between using yapf and any other linter following PEP 8?
Currently I am using a 120 line limit, I will switch to 80. 

- I am using Epytest docstring notation. Will switch to numpy in the future and look into a way to unify. I don't think it should be difficult. 

After clarifications of questions I will follow Ian's suggestion and rebase the PR with the chickpea module refactored into legume and unified docstrings.

**Comment by momchilmm** [comment]
Hey,

> * This is an artifact of internal development, I agree it should be changed. There are a couple ways to do this, one is to move the chickpea module under the legume package the other is to forgoe the chickpea name altogether and place everything under legume directly. Which would you suggest?

yeah, I can see how it came about, but I don't think there's a need for a `chickpea` namespace at all. There's already `legume.utils` where `chickpea.utils` can move (or we can make a `utils` folder if you'd like to separate some things out), and `chickpea.field` can just be moved as `legume.field`, or maybe some of it can go in `viz`, not sure.

> * I am using PyCharm as my developing environment which has its own default linter following the PEP 8 style guide. Yapf can be integrated into it. @ianwilliamson what is the difference between using yapf and any other linter following PEP 8?
>   Currently I am using a 120 line limit, I will switch to 80.

I can lint the main code and push an update on the weekend. Then if we use the same linting hopefully only the functional changes will remain.

> * I am using Epytest docstring notation. Will switch to numpy in the future and look into a way to unify. I don't think it should be difficult.

Thanks!

**Comment by StephenJamesCashen** [comment]
Sounds good. I agree with your assessment WRT chickpea namespace. I will refactor the chickpea modules into the legume namespace. After you push the linting update this weekend I will make a new PR with the proposed changes. And match your code formatting. 

Will keep this PR open in case other issues are noticed in the mean time.

**Comment by ianwilliamson** [comment]
> @ianwilliamson what is the difference between using yapf and any other linter following PEP 8?

In theory there should be no difference but they will all have their own config files which could have subtle differences. The reason I suggested `yapf` was that it's open source and we can standardize on a command to run rather than trying to keep a consistent formatting config.

**Comment by momchilmm** [comment]
Ok I gave it some thought and decided to go with the default yapf PEP8 configuration. This is supposed to also have a 79 characters line limit but for some reason it left some lines e.g. in `matrix_elements.py` a little longer than that? No idea.

Could you try applying this to your code and then also doing the reorganization we discussed above and re-make the PR? Thanks!

**Comment by StephenJamesCashen** [comment]
Great. Will do.

**Pull request closed without merging**
